## IDBM 영화 순위 분석

## IMDB Top 250 Movies
### About Dataset
This dataset is having the data of the top 250 Movies as per their IMDB rating listed on the official website of IMDB

### Features

rank - Movie Rank as per IMDB rating <br>
movie_id - Movie ID <br>
title - Name of the Movie <br>
year - Year of Movie release <br>
link - URL for the Movie <br>
imdb_votes - Number of people who voted for the IMDB rating <br>
imdb_rating - Rating of the Movie <br>
certificate - Movie Certification <br>
duration - Duration of the Movie <br>
genre - Genre of the Movie <br>
cast_id - ID of the cast member who have worked on the Movie <br>
cast_name - Name of the cast member who have worked on the Movie <br>
director_id - ID of the director who have directed the Movie <br>
director_name - Name of the director who have directed the Movie <br>
writer_id - ID of the writer who have wrote script for the Movie <br>
writer_name - Name of the writer who have wrote script for the Movie <br>
storyline - Storyline of the Movie <br>
user_id - ID of the user who wrote review for the Movie <br>
user_name - Name of the user who wrote review for the Movie <br>
review_id - ID of the user review <br>
review_title - Short review <br>
review_content - Long review <br>

### 분석
- 어떤 장르의 영화가 많은 지
- 투표 수에 따른 순위
- 어느 년도에 출시된 영화가 많은 지
- 어느 감독의 영화가 많은 지

In [113]:
import pandas as pd

df = pd.read_csv('../data/movies.csv')

In [114]:
df.head()

,rank,movie_id,title,year,link,imbd_votes,imbd_rating,certificate,duration,genre,...,director_id,director_name,writer_id,writer_name,storyline,user_id,user_name,review_id,review_title,review_content
0,1,tt0111161,The Shawshank Redemption,1994,https://www.imdb.com/title/tt0111161,"2,711,075",9.3,R,2h 22m,Drama,...,nm0001104,Frank Darabont,"nm0000175,nm0001104","Stephen King,Frank Darabont","Over the course of several years, two convicts...","ur16161013,ur15311310,ur0265899,ur16117882,ur1...","hitchcockthelegend,Sleepin_Dragon,EyeDunno,ale...","rw2284594,rw6606154,rw1221355,rw1822343,rw1288...","Some birds aren't meant to be caged.,An incred...",The Shawshank Redemption is written and direct...
1,2,tt0068646,The Godfather,1972,https://www.imdb.com/title/tt0068646,"1,882,829",9.2,R,2h 55m,"Crime,Drama",...,nm0000338,Francis Ford Coppola,"nm0701374,nm0000338","Mario Puzo,Francis Ford Coppola",The aging patriarch of an organized crime dyna...,"ur24740649,ur86182727,ur15794099,ur15311310,ur...","CalRhys,andrewburgereviews,gogoschka-1,Sleepin...","rw3038370,rw4756923,rw4059579,rw6568526,rw1897...","The Pinnacle Of Flawless Films!,An offer so go...",'The Godfather' is the pinnacle of flawless fi...
2,3,tt0468569,The Dark Knight,2008,https://www.imdb.com/title/tt0468569,"2,684,051",9.0,PG-13,2h 32m,"Action,Crime,Drama",...,nm0634240,Christopher Nolan,"tt0468569,nm0634300,nm0634240,nm0275286,tt0468569","Writers,Jonathan Nolan,Christopher Nolan,David...",When the menace known as the Joker wreaks havo...,"ur87850731,ur1293485,ur129557514,ur12449122,ur...","MrHeraclius,Smells_Like_Cheese,dseferaj,little...","rw5478826,rw1914442,rw6606026,rw1917099,rw5170...","The Dark Knight,The Batman of our dreams! So m...","Confidently directed, dark, brooding, and pack..."
3,4,tt0071562,The Godfather Part II,1974,https://www.imdb.com/title/tt0071562,"1,285,350",9.0,R,3h 22m,"Crime,Drama",...,nm0000338,Francis Ford Coppola,"nm0000338,nm0701374","Francis Ford Coppola,Mario Puzo",The early life and career of Vito Corleone in ...,"ur0176092,ur0688559,ur92260614,ur0200644,ur117...","Nazi_Fighter_David,tfrizzell,umunir-36959,DanB...","rw0135607,rw0135487,rw5049900,rw0135526,rw0135...",Breathtaking in its scope and tragic grandeur....,"Coppola's masterpiece is rivaled only by ""The ..."
4,5,tt0050083,12 Angry Men,1957,https://www.imdb.com/title/tt0050083,"800,954",9.0,Approved,1h 36m,"Crime,Drama",...,nm0001486,Sidney Lumet,nm0741627,Reginald Rose,The jury in a New York City murder trial is fr...,"ur1318549,ur0643062,ur0688559,ur20552756,ur945...","uds3,tedg,tfrizzell,TheLittleSongbird,henrique...","rw0060044,rw0060025,rw0060034,rw2262425,rw5448...","The over-used term ""classic movie"" really come...",This once-in-a-generation masterpiece simply h...

In [115]:
df.columns

Index(['rank', 'movie_id', 'title', 'year', 'link', 'imbd_votes',
       'imbd_rating', 'certificate', 'duration', 'genre', 'cast_id',
       'cast_name', 'director_id', 'director_name', 'writer_id', 'writer_name',
       'storyline', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content'],
      dtype='object')

In [116]:
# 필요한 컬럼만 슬라이싱
data = df[['rank', 'movie_id', 'title', 'year', 'link', 'imbd_votes', 'imbd_rating', 'duration', 'genre', 'cast_id', 'cast_name', 'director_id', 'director_name', 'writer_id', 'writer_name',
       'storyline']]

In [117]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rank           250 non-null    int64
 1   movie_id       250 non-null    object
 2   title          250 non-null    object
 3   year           250 non-null    int64
 4   link           250 non-null    object
 5   imbd_votes     250 non-null    object
 6   imbd_rating    250 non-null    float64
 7   duration       250 non-null    object
 8   genre          250 non-null    object
 9   cast_id        250 non-null    object
 10  cast_name      250 non-null    object
 11  director_id    250 non-null    object
 12  director_name  250 non-null    object
 13  writer_id      250 non-null    object
 14  writer_name    250 non-null    object
 15  storyline      250 non-null    object
dtypes: float64(1), int64(2), object(13)
memory usage: 31.4+ KB

In [118]:
# 결측치 확인
data.isnull().sum()

rank             0
movie_id         0
title            0
year             0
link             0
imbd_votes       0
imbd_rating      0
duration         0
genre            0
cast_id          0
cast_name        0
director_id      0
director_name    0
writer_id        0
writer_name      0
storyline        0
dtype: int64

* imbd_votes: 정수형 변환

In [119]:
data['imbd_votes'][0] # ',' 를 없애야 int로 변환가능

'2,711,075'

In [120]:
# 천 단위 콤마(,) 삭제 후 정수형 변환
data['imbd_votes'] = data['imbd_votes'].str.replace(',', '').astype('int64')

C:\Users\Playdata\AppData\Local\Temp\ipykernel_10896\2550449298.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['imbd_votes'] = data['imbd_votes'].str.replace(',', '').astype('int64')

In [121]:
data['imbd_votes'].head()

0    2711075
1    1882829
2    2684051
3    1285350
4     800954
Name: imbd_votes, dtype: int64

In [124]:
data.head()

,rank,movie_id,title,year,link,imbd_votes,imbd_rating,duration,genre,cast_id,cast_name,director_id,director_name,writer_id,writer_name,storyline
0,1,tt0111161,The Shawshank Redemption,1994,https://www.imdb.com/title/tt0111161,2711075,9.3,2h 22m,Drama,"nm0000209,nm0000151,nm0348409,nm0006669,nm0000...","Tim Robbins,Morgan Freeman,Bob Gunton,William ...",nm0001104,Frank Darabont,"nm0000175,nm0001104","Stephen King,Frank Darabont","Over the course of several years, two convicts..."
1,2,tt0068646,The Godfather,1972,https://www.imdb.com/title/tt0068646,1882829,9.2,2h 55m,"Crime,Drama","nm0000008,nm0000199,nm0001001,nm0144710,nm0000...","Marlon Brando,Al Pacino,James Caan,Richard S. ...",nm0000338,Francis Ford Coppola,"nm0701374,nm0000338","Mario Puzo,Francis Ford Coppola",The aging patriarch of an organized crime dyna...
2,3,tt0468569,The Dark Knight,2008,https://www.imdb.com/title/tt0468569,2684051,9.0,2h 32m,"Action,Crime,Drama","nm0000288,nm0005132,nm0001173,nm0000323,nm0350...","Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",nm0634240,Christopher Nolan,"tt0468569,nm0634300,nm0634240,nm0275286,tt0468569","Writers,Jonathan Nolan,Christopher Nolan,David...",When the menace known as the Joker wreaks havo...
3,4,tt0071562,The Godfather Part II,1974,https://www.imdb.com/title/tt0071562,1285350,9.0,3h 22m,"Crime,Drama","nm0000199,nm0000380,nm0000473,nm0000134,nm0001...","Al Pacino,Robert Duvall,Diane Keaton,Robert De...",nm0000338,Francis Ford Coppola,"nm0000338,nm0701374","Francis Ford Coppola,Mario Puzo",The early life and career of Vito Corleone in ...
4,5,tt0050083,12 Angry Men,1957,https://www.imdb.com/title/tt0050083,800954,9.0,1h 36m,"Crime,Drama","nm0000842,nm0275835,nm0002011,nm0550855,nm0001...","Martin Balsam,John Fiedler,Lee J. Cobb,E.G. Ma...",nm0001486,Sidney Lumet,nm0741627,Reginald Rose,The jury in a New York City murder trial is fr...

In [125]:
data.to_csv('../data/movie_added.csv', index = False)

In [144]:
data.columns

Index(['rank', 'movie_id', 'title', 'year', 'link', 'imbd_votes',
       'imbd_rating', 'duration', 'genre', 'cast_id', 'cast_name',
       'director_id', 'director_name', 'writer_id', 'writer_name',
       'storyline'],
      dtype='object')

In [130]:
added = pd.read_csv('../data/movie_added.csv')

,rank,movie_id,title,year,link,imbd_votes,imbd_rating,duration,genre,cast_id,cast_name,director_id,director_name,writer_id,writer_name,storyline
18,19,tt0114369,Se7en,1995,https://www.imdb.com/title/tt0114369,1674020,8.6,2h 7m,"Crime,Drama,Mystery","nm0000151,nm0001825,nm0669254,nm0000093,nm0000...","Morgan Freeman,Andrew Kevin Walker,Daniel Zaca...",nm0000399,David Fincher,nm0001825,Andrew Kevin Walker,"Two detectives, a rookie and a veteran, hunt a..."
39,40,tt0114814,The Usual Suspects,1995,https://www.imdb.com/title/tt0114814,1095033,8.5,1h 46m,"Crime,Drama,Mystery","nm0000286,nm0000321,nm0001125,nm0001629,nm0000...","Stephen Baldwin,Gabriel Byrne,Benicio Del Toro...",nm0001741,Bryan Singer,nm0003160,Christopher McQuarrie,A sole survivor tells of the twisty events lea...
73,74,tt0114709,Toy Story,1995,https://www.imdb.com/title/tt0114709,1005591,8.3,1h 21m,"Animation,Adventure,Comedy","nm0000158,nm0000741,nm0725543,nm0001815,nm0001...","Tom Hanks,Tim Allen,Don Rickles,Jim Varney,Wal...",nm0005124,John Lasseter,"tt0114709,nm0005124,nm0230032,nm0004056,tt0114709","Writers,John Lasseter,Pete Docter,Andrew Stanton,",A cowboy doll is profoundly threatened and jea...
75,76,tt0112573,Braveheart,1995,https://www.imdb.com/title/tt0112573,1046807,8.4,2h 58m,"Biography,Drama,History","nm0732703,nm0492566,nm0625729,nm0181920,nm0569...","James Robinson,Sean Lawlor,Sandy Nelson,James ...",nm0000154,Mel Gibson,nm0908824,Randall Wallace,Scottish warrior William Wallace leads his cou...
108,109,tt0113277,Heat,1995,https://www.imdb.com/title/tt0113277,664714,8.3,2h 50m,"Action,Crime,Drama","nm0000199,nm0000134,nm0000174,nm0000685,nm0001...","Al Pacino,Robert De Niro,Val Kilmer,Jon Voight...",nm0000520,Michael Mann,nm0000520,Michael Mann,A group of high-end professional thieves start...
135,136,tt0112641,Casino,1995,https://www.imdb.com/title/tt0112641,528069,8.2,2h 58m,"Crime,Drama","nm0000134,nm0000232,nm0000582,nm0000249,nm0725...","Robert De Niro,Sharon Stone,Joe Pesci,James Wo...",nm0000217,Martin Scorsese,"nm0683380,nm0000217","Nicholas Pileggi,Martin Scorsese","A tale of greed, deception, money, power, and ..."
178,179,tt0112471,Before Sunrise,1995,https://www.imdb.com/title/tt0112471,315432,8.1,1h 41m,"Drama,Romance","nm0000160,nm0000365,nm0248600,nm0702541,nm0115...","Ethan Hawke,Julie Delpy,Andrea Eckert,Hanno Pö...",nm0000500,Richard Linklater,"nm0000500,nm0471811","Richard Linklater,Kim Krizan",A young man and woman meet on a train in Europ...
228,229,tt0113247,La haine,1995,https://www.imdb.com/title/tt0113247,178165,8.1,1h 38m,"Crime,Drama","nm0001993,nm0468003,nm0846548,nm0315760,nm0813...","Vincent Cassel,Hubert Koundé,Saïd Taghmaoui,Ab...",nm0440913,Mathieu Kassovitz,nm0440913,Mathieu Kassovitz,24 hours in the lives of three young men in th...

### NOTE

In [138]:
year_count = added['year'].value_counts()[:10]

In [139]:
year_count = year_count.reset_index()
year_count_df = pd.DataFrame(year_count)
year_count_df = year_count_df.rename(columns={'year':'count', 'index':'year'})
year_count_df['year'].to_list()

[1995, 2004, 2009, 1957, 2003, 2019, 1999, 1975, 2007, 2011]

In [91]:
new_list = []
for i, year in enumerate(year_count.index):
    new_list.append(str(i)+'위('+str(year)+')')
new_list

['0위(1995)',
 '1위(2004)',
 '2위(2009)',
 '3위(1957)',
 '4위(2003)',
 '5위(2019)',
 '6위(1999)',
 '7위(1975)',
 '8위(2007)',
 '9위(2011)']

In [92]:
year_count.index = new_list
year_count

0위(1995)    8
1위(2004)    7
2위(2009)    6
3위(1957)    6
4위(2003)    6
5위(2019)    6
6위(1999)    6
7위(1975)    5
8위(2007)    5
9위(2011)    5
Name: year, dtype: int64

In [ ]:
# year_count_sorted = year_count.sort_values(ascending=False)
# st.bar_chart(year_count_sorted, x = 'year')

- 인덱스 입력해서 데이터 추출하기

In [143]:
added.loc[6]['link']

'https://www.imdb.com/title/tt0167260'